### PR TITLE
Prevent duplicate form submissions with JavaScript

### PR DESCRIPTION
**Pull request by rjkip**

### CODE REVIEW

**Comment by rjkip** [comment]
@DRvanR this

**Comment by DRvanR** [comment]
As the same must be used on all forms (so also RA/GW), might be an idea to just include it in https://github.com/SURFnet/Stepup-bundle and include that JS in the main templates in the apps?

**Comment by rjkip** [comment]
weeee @DRvanR

**Comment by DRvanR** [comment]
bleergh

**Comment by DRvanR** [comment]
oh, eeeh, and saddas

**Pull request merged**
