### PR TITLE
Audit log WIP

### PR DESCRIPTION
**Pull request by rjkip**
- [x] Revert to `surfnet/stepup-middleware-client-bundle:dev-develop` after merging https://github.com/SURFnet/Stepup-Middleware-clientbundle/pull/23

### CODE REVIEW

**Comment by rjkip** [comment]
:eyeglasses: @DRvanR

**Comment by DRvanR** [comment]
:+1:

**Comment by rjkip** [comment]
Better?

**Comment by DRvanR** [comment]
Shouldn't the revoke command be a MiddlewareClientBundle command? Other than that, :+1:

**Comment by DRvanR** [comment]
As you just informed me otherwise, disregard my previous command, I'll eat a snickers and respond "much better" rather than acting like a diva :wink:

**Pull request merged**
