### PR TITLE
Updated Mopa BootstrapBundle

### PR DESCRIPTION
**Pull request by DRvanR**

### CODE REVIEW

**Comment by DRvanR** [comment]
@rjkip

**Comment by rjkip** [comment]
Minor thing, but `dev-master` has an alias of `3.x-dev`. Would it be wise to require `~3@dev` as to prevent people pulling in 4.x code?

**Comment by DRvanR** [comment]
you're right

**Comment by DRvanR** [comment]
@rjkip as requested :smile:

**Comment by rjkip** [comment]
:+1:

**Pull request merged**
